Creating CRUD ops for product groups
fifty-git/bb-content-manager-api pull request #2
Opened 2023-10-04 17:15 UTC by JesusOrmaza

2023-10-04 20:23 UTC, jcdaniel14 commented on src/core/application/groups-service.ts
> +  const { parent_group_id } = group;
Don't use the json variable here because its of type `any`. Use `validation.data` instead which is the same but with typings after the zod validation is successful. It helps maintainability

2023-10-04 20:27 UTC, jcdaniel14 commented on src/core/application/groups-service.ts
> +  if (!groupExists || groupExists.length === 0) return c.json({ msg: "Group not found" }, 404);
You can move this validation to the datastore class so that this function will always return either a group object or null:
`if (!groupExists || groupExists.length === 0)`

It would be something like this:
```
static async getGroupById(group_id: number) {
    const results = await db
      .select({ group_id: groups.group_id, name: groups.name, parent_group_id: groups.parent_group_id })
      .from(groups)
      .where(eq(groups.group_id, group_id)) // Filtrar por group_id
      .prepare()
      .execute();
    if (!results || results.length === 0) return null;
    return results[0];
  }
```

That way the signature of the datastore function will always return null or the object and further usages will just validate when it is null.

2023-10-04 20:28 UTC, jcdaniel14 commented on src/core/application/groups-service.ts
> +    if (!parentGroup || parentGroup.length === 0) return c.json({ msg: "Parent Group not found" }, 400);
This validation can also go in the datastore class function, just check if it is null

2023-10-04 20:32 UTC, jcdaniel14 commented on src/core/application/groups-service.ts
> +  const groupExists = await GroupsDS.getGroupById(groupId);
You can change this variable name to just group because groupExists sounds like its a boolean

2023-10-04 20:36 UTC, jcdaniel14 commented on src/core/application/groups-service.ts
> +  return c.json({ msg: "Group deleted successfully" }, 204);
You can return null instead of that msg because a 204 code means no content and the browser will ignore the json

2023-10-04 20:37 UTC, jcdaniel14 commented on src/core/application/groups-service.ts
> +  const { parent_group_id } = newGroup;
Same here you can replace newGroup with validation.data which has the typings you have validated.

2023-10-04 20:41 UTC, jcdaniel14 commented on src/core/domain/groups/entity.ts
> +  parent_group_id?: number | null;
Any reason both fields are optional?, also if parent_group_id is optional then null is redundant, it'll be inferred as undefined which is almost the same for the purpose of checking its existence.

2023-10-04 20:41 UTC, jcdaniel14 commented on src/core/domain/groups/entity.ts
> +  parent_group_id?: number | null;
null is redundant here if parent_group_id is optional

2023-10-04 20:43 UTC, jcdaniel14 commented on src/core/domain/groups/validator/create-group-validator.ts
> +    .max(50, { message: "Group name must be at maximum of 50 chars" }),
I think this will let through a name with an empty string

2023-10-04 20:45 UTC, jcdaniel14 commented on src/core/infrastructure/drizzle/groups.ts
> +              subGroups.map((group) => group.group_id),
You already computed this in the subGroupsIDs variable

2023-10-04 20:45 UTC, jcdaniel14 commented on src/core/infrastructure/drizzle/groups.ts
> +      await tx.update(groups).set({ status: "inactive" }).where(eq(groups.group_id, group_id)).execute();
You already disabled group_id in the previous sql update. Check `inArray`

2023-10-04 20:46 UTC, jcdaniel14 commented on src/core/infrastructure/drizzle/groups.ts
> +              subGroups.map((group) => group.group_id),
Same here, its already computed

2023-10-04 20:46 UTC, jcdaniel14 commented on src/core/infrastructure/drizzle/groups.ts
> +      await tx.delete(groups).where(eq(groups.group_id, group_id)).execute();
Same here its already included in the previous delete clause

2023-10-04 20:49 UTC, jcdaniel14 commented on src/core/infrastructure/drizzle/groups.ts
> +          .execute();
you can add .prepare() before .execute() as a performance recommendation on [DrizzleORM docs](https://orm.drizzle.team/docs/perf-queries). It doesn't require any other changes

2023-10-04 20:49 UTC, jcdaniel14 commented on src/core/infrastructure/drizzle/groups.ts
> +    const prepared = db.update(groups).set(group).where(eq(groups.group_id, group_id));
you're missing the .prepare() call here

2023-10-04 20:50 UTC, jcdaniel14 commented on src/core/infrastructure/drizzle/groups.ts
> +          .execute();
Same here, you can add the .prepare() call

2023-10-04 20:51 UTC, jcdaniel14 requested changes
Please check the comments

2023-10-06 18:36 UTC, JesusOrmaza commented on src/core/infrastructure/drizzle/groups.ts
> +      await tx.update(groups).set({ status: "inactive" }).where(eq(groups.group_id, group_id)).execute();
In this line I am updating the parent groups by itself, the las line were only considered the subgroups.

2023-10-06 18:36 UTC, JesusOrmaza commented on src/core/infrastructure/drizzle/groups.ts
> +      await tx.delete(groups).where(eq(groups.group_id, group_id)).execute();
In this line I am deleting the parent group by itself, the las line were only considered the subgroups.

2023-10-06 20:41 UTC, merged